name = "SciPy"
uuid = "ebc72ef8-9537-4fb0-b64e-ac76025fed2d"
authors = ["Atsushi Sakai <asakai.amsl+github@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
