version: 2.1

jobs:
  build_doc:
    docker:
      - image: julia:latest
    steps:
      - checkout
      - run:
          name: install git
          command: apt-get update && apt-get install -y git
workflows:
  main:
    jobs:
      - build_doc
