version: 2.1

jobs:
  build_docs:
    docker:
      - image: julia:latest
    steps:
      - checkout
      - run:
          name: Build docs
          command: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          command: julia --project=docs docs/make.jl
      - store_artifacts:
          path: docs/build/
          destination: html

workflows:
  main:
    jobs:
      - build_docs
