version: 2.1

jobs:
  build_doc:
    docker:
      - image: julia:latest
    steps:
      - run:
          name: upgrade all
          command: apt-get update && apt-get upgrade && apt-get dist-upgrade
      - run:
          name: install git
          command: apt-get install -y git
      - checkout
      - run:
          name: install package
          command: julia --project=docs -e 'using Pkg; 
            Pkg.develop(PackageSpec(path=pwd())); 
            Pkg.instantiate(); 
            Pkg.add("PyPlot");
            Pkg.add("Distributions");
            ENV["PYTHON"] = "";
            Pkg.add("Conda");
            Pkg.add("PyCall");
            Pkg.build("PyCall");
            Pkg.build("Conda");
            using PyCall;
            using Conda;
            Conda.add("gcc=12.1.0"; channel="conda-forge");
            Conda.add("scikit-image");
            Conda.add("scipy=1.8.0");
            '
      - run:
          name: Build docs
          command: julia --project=docs docs/make.jl
          environment:
            CI: true
      - store_artifacts:
          path: docs/build/
          destination: html

workflows:
  main:
    jobs:
      - build_doc
