version: 2.1

jobs:
  build_doc:
    docker:
      - image: julia:latest
    steps:
      - run:
          name: add toolchain repo
          command: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - run:
          name: upgrade all
          command: apt-get update && apt-get upgrade && apt-get dist-upgrade
      - run:
          name: install git
          command: apt-get install -y git
      - run:
          name: install libstdc
          command: apt-get install libstdc++6
      - checkout
      - run:
          name: install package
          command: julia --project=docs -e 'using Pkg; 
            Pkg.develop(PackageSpec(path=pwd())); 
            Pkg.instantiate(); 
            Pkg.add("PyPlot");
            Pkg.add("Distributions");
            '
      - run:
          name: Build docs
          command: julia --project=docs docs/make.jl
          environment:
            CI: true
      - store_artifacts:
          path: docs/build/
          destination: html

workflows:
  main:
    jobs:
      - build_doc
